/* SPORT GOOD DEAL — lecteur indépendant du contenu. Chaque page est dans pages/NN-....js. */
(() => {
"use strict";
const pages=window.SGD_PAGES || [];
const book=document.getElementById("book"),left=document.getElementById("left-page"),right=document.getElementById("right-page"),leaf=document.getElementById("flip-sheet"),count=document.getElementById("page-count"),progress=document.getElementById("progress"),toc=document.getElementById("toc-overlay"),print=document.getElementById("print-pages");
const prev=document.getElementById("previous"),next=document.getElementById("next"),tocGrid=document.getElementById("toc-grid");
let current=0,busy=false;
const small=()=>window.matchMedia("(max-width:780px)").matches;
const step=()=>small()?1:2;
const snap=(n)=>small()?n:Math.floor(n/2)*2;
const pageHTML=(p,i)=>!p?"":p.html.replace(/__PN__/g,String(i+1).padStart(2,"0"));
function markup(p,i){return p?'<div class="sheet-pad">'+pageHTML(p,i)+'<div class="page-number"><span>SPORT GOOD DEAL / GUIDE DU SKI</span><span>'+String(i+1).padStart(2,"0")+' / '+String(pages.length).padStart(2,"0")+'</span></div></div>':""}
function applyPage(el,p,i){el.innerHTML=markup(p,i);el.setAttribute("aria-label",p?p.title:"Page vierge");}
function update(){applyPage(left,pages[current],current);applyPage(right,pages[current+1],current+1);count.textContent=(small()?String(current+1).padStart(2,"0"):String(current+1).padStart(2,"0")+"–"+String(Math.min(pages.length,current+2)).padStart(2,"0"))+" / "+String(pages.length).padStart(2,"0");prev.disabled=current===0;next.disabled=current+step()>=pages.length;progress.style.width=(Math.min(pages.length,current+step())/pages.length*100)+"%";document.title=(pages[current]?.title||"Le guide")+" — SPORT GOOD DEAL";bindInteractive();}
function renderAt(i){current=Math.max(0,Math.min(pages.length-1,snap(i)));update();history.replaceState(null,"","#page="+(current+1));}
function go(dir){const target=current+dir*step();if(busy||target<0||target>=pages.length)return;busy=true;if(small()||window.matchMedia("(prefers-reduced-motion:reduce)").matches){renderAt(target);busy=false;return;}leaf.innerHTML='<div class="flip-side flip-front">'+markup(pages[dir>0?current+1:current],dir>0?current+1:current)+'</div><div class="flip-side flip-back">'+markup(pages[dir>0?target:target+1],dir>0?target:target+1)+'</div>';book.classList.add(dir>0?"is-forward":"is-backward");setTimeout(()=>{renderAt(target)},360);setTimeout(()=>{book.classList.remove("is-forward","is-backward");leaf.innerHTML="";busy=false},750);}
function bindInteractive(){
 document.querySelectorAll("[data-spot]").forEach(btn=>btn.addEventListener("click",()=>{const terms={tip:["Spatule","La partie avant du ski. Sa forme et son relèvement influencent le contact avec la neige et l'entrée de virage."],waist:["Patin","La zone la plus étroite sous la chaussure. Plus la largeur augmente, plus la rapidité de changement de carre peut diminuer, tandis que la portance s'améliore."],tail:["Talon","La partie arrière du ski, qui influence la sortie de virage, la stabilité et la faculté de pivot."],sidecut:["Lignes de cotes","Largeurs mesurées à la spatule, au patin et au talon. Exemple fictif : 124–78–109 mm. Le rayon annoncé dépend aussi de la longueur du ski."],binding:["Fixation","Elle transmet les appuis tout en assurant une fonction de déclenchement. Son réglage est une opération réservée au personnel qualifié."]};const [h,p]=terms[btn.dataset.spot];const box=document.querySelector(".term-display");if(box){box.querySelector("strong").textContent=h;box.querySelector("p").textContent=p;}document.querySelectorAll("[data-spot]").forEach(b=>b.setAttribute("aria-pressed",String(b===btn)));}));
 document.querySelectorAll("[data-profile]").forEach(btn=>btn.addEventListener("click",()=>{const dict={classic:["Cambre classique","Zone centrale relevée sans charge. Sous l'appui du skieur, le ski se déforme et répartit la pression.","M38 88 Q70 141 140 141 C240 141 245 123 340 123 C435 123 440 141 540 141 Q610 141 642 88"],front:["Rocker avant","Spatule relevée plus tôt, associée ici à un cambre traditionnel modéré.","M38 65 Q95 141 191 141 C265 141 282 127 340 127 C407 127 440 141 540 141 Q610 141 642 88"],double:["Double rocker","Spatule et talon relevés plus tôt : le ski peut pivoter plus facilement.","M38 65 Q98 141 190 141 C255 141 292 130 340 130 C390 130 425 141 490 141 Q585 141 642 65"],full:["Full rocker","Profil globalement inversé, généralement orienté vers le pivot et la neige souple.","M38 72 Q190 134 340 141 Q490 134 642 72"]};let [a,b,path]=dict[btn.dataset.profile];const scope=btn.closest(".sheet");scope.querySelector(".profile-key strong").textContent=a;scope.querySelector(".profile-key p").textContent=b;scope.querySelector(".profile-svg-path").setAttribute("d",path);scope.querySelectorAll("[data-profile]").forEach(x=>x.setAttribute("aria-pressed",String(x===btn)));}));
 document.querySelectorAll(".page-jump").forEach(btn=>btn.addEventListener("click",()=>{const n=Number(btn.dataset.jump);closeToc();renderAt(n)}));
 const practice=document.querySelector("#practice-select"),level=document.querySelector("#level-select");if(practice&&level){const check=()=>{const map={piste:["Piste loisir ou piste polyvalente","Chercher un flex adapté au niveau et au gabarit et une longueur cohérente avec le modèle."],poly:["All-mountain","Évaluer la proportion réelle de piste et de neige non damée : largeur et profil doivent suivre."],freeride:["Freeride","Privilégier un modèle adapté à la neige souple et à la technique du skieur."],nordique:["Fond classique ou skating","Distinguer la technique pratiquée, puis sélectionner longueur et cambre en fonction du poids."],rando:["Randonnée alpine","Étudier le compromis montée/descente et vérifier compatibilité des systèmes."]};let [t,d]=map[practice.value];if(practice.value==="piste"&&level.value==="sportif"){t="Piste performance (à confirmer)";d="Pour un skieur réellement confirmé cherchant de la tenue et de la relance, comparer les skis plus structurés.";}document.getElementById("selection-title").textContent=t;document.getElementById("selection-text").textContent=d+" Ce n'est pas une prescription de longueur ni un choix définitif.";};practice.addEventListener("change",check);level.addEventListener("change",check);check();}
}
function closeToc(){toc.classList.remove("open");document.getElementById("toc-button").focus();}
document.getElementById("toc-button").addEventListener("click",()=>toc.classList.add("open"));
document.getElementById("toc-close").addEventListener("click",closeToc);
toc.addEventListener("click",e=>{if(e.target===toc)closeToc()});
prev.addEventListener("click",()=>go(-1));next.addEventListener("click",()=>go(1));
document.getElementById("print-button").addEventListener("click",()=>window.print());
window.addEventListener("keydown",e=>{if(e.key==="Escape"&&toc.classList.contains("open")){closeToc();return;}if(toc.classList.contains("open"))return;if(["INPUT","SELECT","TEXTAREA"].includes(document.activeElement?.tagName))return;if(e.key==="ArrowRight")go(1);if(e.key==="ArrowLeft")go(-1)});
window.addEventListener("resize",()=>{const n=snap(current);if(n!==current){current=n;}update()});
window.addEventListener("hashchange",()=>{const match=location.hash.match(/^#page=(\d+)$/);if(match)renderAt(Number(match[1])-1)});
if(!pages.length){left.textContent="Le contenu n'est pas disponible. Vérifier les fichiers pages/.";return;}
pages.forEach((p,i)=>{const a=document.createElement("button");a.className="toc-choice page-jump";a.dataset.jump=i;a.innerHTML='<span class="toc-n">'+String(i+1).padStart(2,"0")+'</span><span><b>'+p.title+'</b><small>'+p.chapter+'</small></span>';tocGrid.append(a);});
print.innerHTML=pages.map((p,i)=>'<div class="print-page"><div class="sheet">'+markup(p,i)+'</div></div>').join("");
const h=location.hash.match(/^#page=(\d+)$/);renderAt(h?Number(h[1])-1:0);
})();